version: "3.9"
    
services: 
  wordpress:
    container_name: wordpresto-wordpress
    depends_on:
      - wordpress-db
    image: wordpress:latest
    volumes:
      - /home/administrator/volumes/wordpresto/wp-content:/var/www/html/wp-content
    ports:
      - ${WORDPRESS_PORT}:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  wordpress-db:
    container_name: wordpresto-wordpress-db
    image: mysql:latest
    volumes:
      - /home/administrator/volumes/wordpresto/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${WORDPRESS_DB_PORT}:3306

  wordpress-db-phpmyadmin:
    container_name: wordpresto-wordpress-db-phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - wordpress-db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - ${WORDPRESS_PHPMYADMIN_PORT}:80

  nginx-proxy-manager:
    container_name: wordpresto-nginx-proxy-manager
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - 80:80
      - ${NGINX_PROXY_MANAGER_PORT}:81
      - 443:443
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: "npm"
    volumes:
      - /home/administrator/volumes/nginx/data:/data
      - /home/administrator/volumes/nginx/letsencrypt:/etc/letsencrypt

  nginx-proxy-manager-db:
    container_name: wordpresto-nginx-proxy-manager-db
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /home/administrator/volumes/nginx/data/mysql:/var/lib/mysql

  portainer:
    container_name: wordpresto-portainer
    image: portainer/portainer-ce:latest
    ports:
      - ${PORTAINER_PORT}:9000
    restart: always
    security_opt:
      - no-new-privileges:false
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/administrator/volumes/portainer/portainer_data:/data