version: '3.2'

services:
  agent:
    restart: always
    container_name: wordpresto-portainer-agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    restart: always
    container_name: wordpresto-portainer
    image: portainer/portainer-ce
    command: -H tcp://agent:9001 --tlsskipverify
    ports:
      - "9000:9000"
    volumes:
      - /home/admin/volumes/portainer/portainer_data:/data