version: "3.9"
    
services:
  db:
    container_name: wordpresto-wordpress-db
    image: mysql:latest
    volumes:
      - /home/administrator/volumes/wordpresto/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    
  wordpress:
    container_name: wordpresto-wordpress
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    # image: wordpress:latest
    volumes:
      - /home/administrator/volumes/wordpresto/wp-content:/var/www/html/wp-content
    ports:
      - "3070:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    container_name: wordpresto-wordpress-db-phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80